Create view VW_Thematique_Semaine as
Select t.LIBELLE_THEMATIQUE,t.NUMERO_THEMATIQUE,s.DATE_DEBUT,s.DATE_FIN,s.NUMERO_SEMAINE
From T_E_THEMATIQUE_THE t
Join T_J_SEMAINE_THEMATIQUE_SET st on st.NUMERO_THEMATIQUE = t.NUMERO_THEMATIQUE
Join T_E_SEMAINE_SEM s on s.NUMERO_SEMAINE = st.NUMERO_SEMAINE;

create view VW_Prestataire_audio as
select concat(RUE," ",VILLE," ",CP),
RAISON_SOCIALE_PRESTA_EXTERNE,
LIBELLE_TYPE_MACHINE,
CODE_QUALITE_TECHNIQUE,
NOM_CONTACT

from T_E_PRESTATAIRE_EXTERNE_EXT  PE
join T_E_PRESTATAIRE_AUDIO_AUD PA on PA.NUMERO_PRESTATAIRE=PE.NUMERO_PRESTATAIRE
join T_E_QUALITE_TECHNIQUE_QUA QT on PA.CODE_QUALITE_TECHNIQUE=QT.CODE_QUALITE_TECHNIQUE
join T_E_TYPE_MACHINE_TYM TM on PA.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
join T_E_ADRESSE_ADR AD on AD.CODE_ADRESSE = PE.CODE_ADRESSE



create view VW_Prestataire_Papier as
select RAISON_SOCIALE_PRESTA_EXTERNE,
concat(RUE," ",VILLE," ",CP),
NOM_CONTACT,
LIBELLE_TYPE_MACHINE,
RECYCLAGE

from T_E_PRESTATAIRE_EXTERNE_EXT PE
join T_E_PRESTATAIRE_PAPIER PP on PP.NUMERO_PRESTATAIRE=PE.NUMERO_PRESTATAIRE
join T_E_TYPE_MACHINE_TYM TM on PP.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
join T_E_ADRESSE_ADR AD on AD.CODE_ADRESSE = PE.CODE_ADRESSE
