drop view VW_Thematique_Semaine;
Create view VW_Thematique_Semaine as
Select t.LIBELLE_THEMATIQUE,t.NUMERO_THEMATIQUE,s.DATE_DEBUT,s.DATE_FIN,s.NUMERO_SEMAINE
From T_E_THEMATIQUE_THE t
    Join T_J_SEMAINE_THEMATIQUE_SET st on st.NUMERO_THEMATIQUE = t.NUMERO_THEMATIQUE
    Join T_E_SEMAINE_SEM s on s.NUMERO_SEMAINE = st.NUMERO_SEMAINE;


drop view VW_Prestataire_audio;
create view VW_Prestataire_audio as
select RUE||' '||VILLE||' '||CP as Adresse,RAISON_SOCIALE,LIBELLE_TYPE_MACHINE,QT.NUMERO_QUALITE_TECHNIQUE,NOM_PRESTATAIRE
from T_E_PRESTATAIRE_EXTERNE_EXT PEX
    join T_E_PRESTATAIRE_AUDIO_AUD PA on PA.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE
    join T_R_QUALITE_TECHNIQUE_QUA QT on PA.NUMERO_QUALITE_TECHNIQUE=QT.NUMERO_QUALITE_TECHNIQUE
    join T_R_TYPE_MACHINE_TYM TM on PA.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
    join T_E_ADRESSE_ADR AD on AD.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    join T_E_PRESTATAIRE_PRE PE on PE.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE;


drop view VW_Prestataire_Papier;
create view VW_Prestataire_Papier as
select RUE||' '||VILLE||' '||CP as Adresse,RAISON_SOCIALE,NOM_PRESTATAIRE,LIBELLE_TYPE_MACHINE,RECYCLAGE
from T_E_PRESTATAIRE_EXTERNE_EXT PEX
    join T_E_PRESTATAIRE_PAPIER_PAP PP on PP.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE
    join T_R_TYPE_MACHINE_TYM TM on PP.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
    join T_E_ADRESSE_ADR AD on AD.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    join T_E_PRESTATAIRE_PRE PE on PE.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE;


drop view VW_Prestataire_Image;
Create view VW_Prestataire_Image as 
Select LOG.LIBELLE_LOGICIEL,LIBELLE_SYSTEME,RUE||' '||VILLE||' '||CP as Adresse, RAISON_SOCIALE
From T_E_PRESTATAIRE_IMAGE_IMA IMA  
    Join T_E_PRESTATAIRE_PRE PRE on PRE.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Join T_E_PRESTATAIRE_EXTERNE_EXT PEX on PEX.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Join T_E_ADRESSE_ADR ADR on ADR.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    Left Join T_J_LOGICIEL_PRESTATAIRE_LPR LPR on LPR.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Left Join T_R_LOGICIEL_LOG LOG on LOG.NUMERO_LOGICIEL = LPR.NUMERO_LOGICIEL
    Left Join T_J_SYSTEME_PRESTATAIRE_SPR SPR on SPR.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Left Join T_R_SYSTEME_SYS S on S.NUMERO_SYSTEME = SPR.NUMERO_SYSTEME;

drop view VW_Thematique_Type_Action;
Create view VW_Thematique_Type_Action as
Select T.NUMERO_THEMATIQUE,
TA1.NUMERO_TYPE_ACTION as Numero_Type_Action_Parent,
TA1.LIBELLE_TYPE_ACTION as Libelle_Type_Action_Parent,
TA1.NUMERO_TYPE_ACTION as Code_Type_Action_Parent,
TA2.NUMERO_TYPE_ACTION as Numero_Type_Action_Enfant,
TA2.LIBELLE_TYPE_ACTION as Libelle_Type_Action_Enfant,
TA2.CODE_TYPE_ACTION as Code_Type_Action_Enfant
From T_E_THEMATIQUE_THE T
Join T_J_DETAIL_THEMATIQUE_DET DT on DT.NUEMRO_THEMATIQUE = T.NUEMRO_THEMATIQUE
Join T_R_TYPE_Action_TAC TA1 on TA1.NUMERO_TYPE_ACTION = DT.NUMERO_TYPE_ACTION
Left Join T_J_Couple_COU C on C.NUMERO_TYPE_ACTION = TA1.NUMERO_TYPE_ACTION
Left Join T_R_Type_Action_TAC TA2 on TA2.NUMERO_TYPE_ACTION = C.NUMERO_TYPE_ACTION;