drop view VW_Thematique_Semaine;
Create view VW_Thematique_Semaine as
Select t.LIBELLE_THEMATIQUE,t.NUMERO_THEMATIQUE,s.DATE_DEBUT,s.DATE_FIN,s.NUMERO_SEMAINE
From T_E_THEMATIQUE_THE t
    Join T_J_SEMAINE_THEMATIQUE_SET st on st.NUMERO_THEMATIQUE = t.NUMERO_THEMATIQUE
    Join T_E_SEMAINE_SEM s on s.NUMERO_SEMAINE = st.NUMERO_SEMAINE;


drop view VW_Prestataire_audio;
create view VW_Prestataire_audio as
select RUE||' '||VILLE||' '||CP as Adresse,RAISON_SOCIALE,LIBELLE_TYPE_MACHINE,QT.NUMERO_QUALITE_TECHNIQUE,NOM_PRESTATAIRE
from T_E_PRESTATAIRE_EXTERNE_EXT PEX
    join T_E_PRESTATAIRE_AUDIO_AUD PA on PA.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE
    join T_R_QUALITE_TECHNIQUE_QUA QT on PA.NUMERO_QUALITE_TECHNIQUE=QT.NUMERO_QUALITE_TECHNIQUE
    join T_R_TYPE_MACHINE_TYM TM on PA.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
    join T_E_ADRESSE_ADR AD on AD.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    join T_E_PRESTATAIRE_PRE PE on PE.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE;


drop view VW_Prestataire_Papier;
create view VW_Prestataire_Papier as
select RUE||' '||VILLE||' '||CP as Adresse,RAISON_SOCIALE,NOM_PRESTATAIRE,LIBELLE_TYPE_MACHINE,RECYCLAGE
from T_E_PRESTATAIRE_EXTERNE_EXT PEX
    join T_E_PRESTATAIRE_PAPIER_PAP PP on PP.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE
    join T_R_TYPE_MACHINE_TYM TM on PP.NUMERO_TYPE_MACHINE=TM.NUMERO_TYPE_MACHINE
    join T_E_ADRESSE_ADR AD on AD.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    join T_E_PRESTATAIRE_PRE PE on PE.NUMERO_PRESTATAIRE=PEX.NUMERO_PRESTATAIRE;


drop view VW_Prestataire_Image;
Create view VW_Prestataire_Image as 
Select LOG.LIBELLE_LOGICIEL,LIBELLE_SYSTEME,RUE||' '||VILLE||' '||CP as Adresse, RAISON_SOCIALE
From T_E_PRESTATAIRE_IMAGE_IMA IMA  
    Join T_E_PRESTATAIRE_PRE PRE on PRE.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Join T_E_PRESTATAIRE_EXTERNE_EXT PEX on PEX.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Join T_E_ADRESSE_ADR ADR on ADR.NUMERO_ADRESSE = PEX.NUMERO_ADRESSE
    Left Join T_J_LOGICIEL_PRESTATAIRE_LPR LPR on LPR.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Left Join T_R_LOGICIEL_LOG LOG on LOG.NUMERO_LOGICIEL = LPR.NUMERO_LOGICIEL
    Left Join T_J_SYSTEME_PRESTATAIRE_SPR SPR on SPR.NUMERO_PRESTATAIRE = IMA.NUMERO_PRESTATAIRE
    Left Join T_R_SYSTEME_SYS S on S.NUMERO_SYSTEME = SPR.NUMERO_SYSTEME
UNION
SELECT LOG.LIBELLE_LOGICIEL,LIBELLE_SYSTEME,' ', RAISON_SOCIALE
FROM T_E_PRESTATAIRE_INTERNE_INT INT
    Join T_E_PRESTATAIRE_PRE PRE on PRE.NUMERO_PRESTATAIRE = INT.NUMERO_PRESTATAIRE
    Join T_J_PRESTA_INT_SYS_PIS PIS ON PIS.NUMERO_PRESTATAIRE = INT.NUMERO_PRESTATAIRE
    Join T_J_PRESTA_INT_LOG_PIL PIL ON PIL.NUMERO_PRESTATAIRE = INT.NUMERO_PRESTATAIRE
    Left Join T_R_LOGICIEL_LOG LOG on LOG.NUMERO_LOGICIEL = PIL.NUMERO_LOGICIEL
    Left Join T_R_SYSTEME_SYS S on S.NUMERO_SYSTEME = PIS.NUMERO_SYSTEME;


drop view VW_Thematique_Type_Action;
Create view VW_Thematique_Type_Action as
Select T.NUMERO_THEMATIQUE,
TA1.NUMERO_TYPE_ACTION as Numero_Type_Action_Parent,
TA1.LIBELLE_TYPE_ACTION as Libelle_Type_Action_Parent,
TA1.NUMERO_TYPE_ACTION as Code_Type_Action_Parent,
TA2.NUMERO_TYPE_ACTION as Numero_Type_Action_Enfant,
TA2.LIBELLE_TYPE_ACTION as Libelle_Type_Action_Enfant,
TA2.NUMERO_TYPE_ACTION as Code_Type_Action_Enfant
From T_E_THEMATIQUE_THE T
    Join T_J_DETAIL_THEMATIQUE_DET DT on DT.NUMERO_THEMATIQUE = T.NUMERO_THEMATIQUE
    Join T_R_TYPE_ACTION_TAC TA1 on TA1.NUMERO_TYPE_ACTION = DT.NUMERO_TYPE_ACTION
    Left Join T_J_COUPLE_COU C on C.NUMERO_TYPE_ACTION = TA1.NUMERO_TYPE_ACTION
    Left Join T_R_TYPE_ACTION_TAC TA2 on TA2.NUMERO_TYPE_ACTION = C.NUMERO_TYPE_ACTION;

drop view VW_action_pub;
CREATE OR REPLACE VIEW VW_action_pub as
SELECT ACT.NUMERO_ACTION_PUBLICITAIRE, SEC.LIBELLE_SECTEUR_ACTIVITE, FOU.NOM_FOURNISSEUR, THE.LIBELLE_THEMATIQUE, GAM.LIBELLE_GAMME, DAC.PRIX_REVIENT_DETAIL_ACTION, DAC.PRIX_VENTE_DETAIL_ACTION, PRO.NOM_PRODUIT
FROM T_E_ACTION_PUBLICITAIRE_ACT ACT
    JOIN T_J_DETAIL_ACTION_DAC DAC on DAC.NUMERO_SECTEUR_ACTIVITE = ACT.NUMERO_SECTEUR_ACTIVITE
    JOIN T_R_SECTEUR_ACTIVITE_SEC SEC on SEC.NUMERO_SECTEUR_ACTIVITE = ACT.NUMERO_SECTEUR_ACTIVITE
    JOIN T_E_GAMME_GAM GAM on GAM.NUMERO_GAMME = ACT.NUMERO_GAMME
    JOIN T_E_THEMATIQUE_THE THE on THE.NUMERO_THEMATIQUE = ACT.NUMERO_THEMATIQUE
    JOIN T_J_PRODUIT_ACTION_PAC PAC on PAC.NUMERO_ACTION_PUBLICITAIRE = ACT.NUMERO_ACTION_PUBLICITAIRE
    JOIN T_E_PRODUIT_PRO PRO on PRO.NUMERO_PRODUIT = PAC.NUMERO_PRODUIT
    JOIN T_E_FOURNISSEUR_FOU FOU on FOU.NUMERO_FOURNISSEUR = ACT.NUMERO_FOURNISSEUR;

drop view VW_fournisseur;
CREATE OR REPLACE VIEW VW_fournisseur as
SELECT FOU.NUMERO_FOURNISSEUR, ENS.NOM_ENSEIGNE, RUE||' '||VILLE||' '||CP as Adresse, GRO.NOM_GROUPE, FOU.NOM_FOURNISSEUR, FOU.PRENOM_FOURNISSEUR, FOU.TELEPHONE_FOURNISSEUR, FOU.MAIL_FOURNISSEUR, BUD.OBJECTIF, BUD.ENGAGE, BUD.FACTURE
FROM T_E_FOURNISSEUR_FOU FOU
    JOIN T_E_ENSEIGNE_ENS ENS ON ENS.NUMERO_ENSEIGNE = FOU.NUMERO_ENSEIGNE
    JOIN T_E_ADRESSE_ADR ADR ON ADR.NUMERO_ADRESSE = FOU.NUMERO_ADRESSE
    JOIN T_E_GROUPE_GRO GRO ON GRO.NUMERO_GROUPE = FOU.NUMERO_GROUPE
    JOIN T_J_BUDGET_BUD BUD ON BUD.NUMERO_FOURNISSEUR = FOU.NUMERO_FOURNISSEUR;
